### ISSUE TITLE
Ajout Meteo : New York

### ISSUE THREAD

**Issue by snybril** [appsgate2015/appsgate#514]

**Comment by snybril** [comment]
La requête arrive bien au server, mais le weatherObserver n'est pas créé,

Exception:
10:43:44.334 [pool-9-thread-9] DEBUG a.l.w.e.impl.WeatherObserverFactory -- createObserver(String location : New York)
10:43:44.352 [pool-9-thread-9] INFO  a.lig.yahoo.impl.YahooWeatherImpl -- addLocation(String placeName: New York )
10:43:44.352 [pool-9-thread-9] TRACE a.lig.yahoo.impl.YahooGeoPlanetImpl -- GetWOEIDFromPlaceName(String placeName : New+York)
10:43:44.353 [pool-9-thread-9] TRACE a.lig.yahoo.impl.YahooGeoPlanetImpl -- GetWOEIDFromPlaceName(...), query URL : http://where.yahooapis.com/v1/places.q(New+York)?appid=LIolTLV34H_riBa5bYkTDWrCutm0j7Ta6Nvzfh1wOp5tBktKEXzSOsKznKPqFzE9Nw-
10:43:44.467 [pool-9-thread-9] TRACE a.lig.yahoo.impl.YahooGeoPlanetImpl -- GetWOEIDFromPlaceName(...), found WOEID : 2459115
10:43:44.467 [pool-9-thread-9] TRACE a.lig.yahoo.impl.YahooWeatherImpl -- Fetching Weather for New York, WOEID : 2459115
10:43:44.637 [pool-9-thread-9] INFO  a.lig.yahoo.impl.YahooWeatherImpl -- Publication date for New York is newer, parsing new Weather Data !
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.valueOf(Integer.java:582)
	at appsgate.lig.yahoo.impl.YahooWeatherParser.parseCurrentConditions(YahooWeatherParser.java:64)
	at appsgate.lig.yahoo.impl.YahooWeatherImpl.__M_fetch(YahooWeatherImpl.java:346)
	at appsgate.lig.yahoo.impl.YahooWeatherImpl.fetch(YahooWeatherImpl.java)
	at appsgate.lig.yahoo.impl.YahooWeatherImpl.__M_addLocation(YahooWeatherImpl.java:196)
	at appsgate.lig.yahoo.impl.YahooWeatherImpl.addLocation(YahooWeatherImpl.java)
	at appsgate.lig.weather.extended.impl.WeatherObserverImpl.__M_start(WeatherObserverImpl.java:86)
	at appsgate.lig.weather.extended.impl.WeatherObserverImpl.start(WeatherObserverImpl.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:237)
	at fr.imag.adele.apam.apform.impl.InstanceCallback.invoke(InstanceCallback.java:186)
	at fr.imag.adele.apam.apform.impl.ApamInstanceManager$Apform.fireCallbacks(ApamInstanceManager.java:604)
	at fr.imag.adele.apam.apform.impl.ApamInstanceManager$Apform.setApamComponent(ApamInstanceManager.java:503)
	at fr.imag.adele.apam.impl.InstanceImpl.register(InstanceImpl.java:210)
	at fr.imag.adele.apam.impl.ImplementationImpl.createInstance(ImplementationImpl.java:198)
	at appsgate.lig.weather.extended.impl.WeatherObserverFactory.__M_createObserver(WeatherObserverFactory.java:236)
	at appsgate.lig.weather.extended.impl.WeatherObserverFactory.createObserver(WeatherObserverFactory.java)
	at appsgate.lig.weather.extended.impl.WeatherObserverFactory.__M_addLocationObserver(WeatherObserverFactory.java:129)
	at appsgate.lig.weather.extended.impl.WeatherObserverFactory.addLocationObserver(WeatherObserverFactory.java)
	at appsgate.lig.ehmi.impl.EHMIProxyImpl.__M_addLocationObserver(EHMIProxyImpl.java:745)
	at appsgate.lig.ehmi.impl.EHMIProxyImpl.addLocationObserver(EHMIProxyImpl.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at appsgate.lig.ehmi.impl.EHMICommand.abstractInvoke(EHMICommand.java:92)
	at appsgate.lig.ehmi.impl.EHMICommand.run(EHMICommand.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
10:43:44.651 [pool-9-thread-9] WARN  a.l.w.e.impl.WeatherObserverFactory -- Unable to create WeatherObserver for New York
1

**Comment by snybril** [comment]
Pas possible de reproduire... Je met ça sur le compte d'un dysfonctionnement passager de Yahoo.
